In [1]:
import tensorflow as tf

### 차원에 따른 텐서 생성

In [2]:
t0 = tf.constant(1)
print(t0)
print(tf.rank(t0))  # 축의 개수를 반환합니다.

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [3]:
t1 = tf.constant([1, 2, 3])
print(t1)
print(tf.rank(t1))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [4]:
t2 = tf.constant([[1, 2, 3], [1, 2, 3]])
print(t2)
print(tf.rank(t2))

tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [8]:
t3 = tf.constant([[[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(t3)
print(tf.rank(t3))

tf.Tensor(
[[[1 2 3]
  [1 2 3]
  [1 2 3]]], shape=(1, 3, 3), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


### 텐서의 타입

In [9]:
# 상수값 2인 텐서 생성
i = tf.constant(2)
print(i)

tf.Tensor(2, shape=(), dtype=int32)


* 타입 int32